name: Harmony CI Workflow

run-name: Fati Harmony

on:
  push:
    branches:
      - fati

jobs:
  building:
    name: Building Angular Project
    runs-on: ubuntu-latest
    steps:

      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: List files in the current directory
        run: ls -la

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Verify Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Change directory to Angular project
        run: |
          cd Frontend
          ls -la

      - name: Install Dependencies for Angular Project
        run: ng install 

      - name: Run Tests for Angular Project
        run: npm test || true

      - name: Lint Angular Project
        run: npm run lint || true

      - name: Run E2E Tests for Angular Project
        run: npm run e2e || true

      - name: Run Security Audit for Angular Project
        run: npm audit || true
          
      - name: Build Angular Project
        run: npm run build --prod



